export const SET_OFFSET = 'SET_OFFSET';
export const SET_CURRENT_PAGE_ELEMENTS = 'SET_CURRENT_PAGE_ELEMENTS';
export const SET_ELEMENTS_PER_PAGE = 'SET_ELEMENTS_PER_PAGE';
export const SET_PAGES_COUNT = 'SET_PAGES_COUNT';
export const SET_ALL_ELEMENTS = 'SET_ALL_ELEMENTS';
export const SET_TOTAL_ELEMENTS_COUNT = 'SET_TOTAL_ELEMENTS_COUNT';


export const FETCH_STATUS = 'FETCH_STATUS';
export const ADD_PERSON = 'ADD_PERSON';
export const POP_UP_STATUS = 'POP_UP_STATUS';
export const SET_POP_UP_PERSON = 'SET_POP_UP_PERSON';
export const DELETE_ALL_PEOPLE = 'DELETE_ALL_PEOPLE';
export const DELETE_FETCHED_DATA = 'DELETE_FETCHED_DATA';